CREATE TYPE "public"."promotion_type" AS ENUM('percentage', 'fixed_amount', 'free_shipping');--> statement-breakpoint
CREATE TYPE "public"."refund_status" AS ENUM('requested', 'approved', 'processing', 'completed', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."return_reason" AS ENUM('wrong_size', 'defective', 'not_as_described', 'changed_mind', 'late_delivery', 'other');--> statement-breakpoint
CREATE TABLE "account" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" uuid NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" uuid NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "promotion_category" (
	"id" serial PRIMARY KEY NOT NULL,
	"category_id" integer NOT NULL,
	"promotion_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "promotion" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "promotion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(128) NOT NULL,
	"code" varchar(64) NOT NULL,
	"description" varchar(255),
	"type" "promotion_type" DEFAULT 'percentage' NOT NULL,
	"discount_rate" numeric(12, 2) NOT NULL,
	"min_order_amount" numeric(12, 2),
	"max_discount_amount" numeric(12, 2),
	"usage_limit" integer,
	"usage_count" integer DEFAULT 0 NOT NULL,
	"per_user_limit" integer DEFAULT 1,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "promotion_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "promotion_usage" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "promotion_usage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"promotion_id" integer NOT NULL,
	"user_id" uuid NOT NULL,
	"order_id" integer,
	"used_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "refund_request" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "refund_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" integer NOT NULL,
	"user_id" uuid NOT NULL,
	"status" "refund_status" DEFAULT 'requested' NOT NULL,
	"reason" "return_reason" NOT NULL,
	"description" text,
	"quantity" integer DEFAULT 1 NOT NULL,
	"refund_amount" numeric(12, 2),
	"stripe_refund_id" varchar(128),
	"admin_notes" text,
	"processed_by" varchar(128),
	"processed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "refund_timeline" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "refund_timeline_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"refund_request_id" integer NOT NULL,
	"action" varchar(64) NOT NULL,
	"notes" text,
	"performed_by" varchar(128),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cart_item" DROP CONSTRAINT "cart_item_user_id_site_users_id_fk";
--> statement-breakpoint
ALTER TABLE "product_collection" DROP CONSTRAINT "product_collection_product_id_product_id_fk";
--> statement-breakpoint
ALTER TABLE "product_collection" DROP CONSTRAINT "product_collection_collection_id_collection_id_fk";
--> statement-breakpoint
ALTER TABLE "user_measurements" DROP CONSTRAINT "user_measurements_user_id_site_users_id_fk";
--> statement-breakpoint
ALTER TABLE "order_items" DROP CONSTRAINT "order_items_order_id_shop_order_id_fk";
--> statement-breakpoint
ALTER TABLE "order_measurements" DROP CONSTRAINT "order_measurements_order_item_id_order_items_id_fk";
--> statement-breakpoint
ALTER TABLE "shop_order" DROP CONSTRAINT "shop_order_user_id_site_users_id_fk";
--> statement-breakpoint
TRUNCATE TABLE "idempotency_keys";--> statement-breakpoint
ALTER TABLE "idempotency_keys" DROP COLUMN "user_id";--> statement-breakpoint
ALTER TABLE "idempotency_keys" ADD COLUMN "user_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "product_configuration" ALTER COLUMN "selected_options" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "site_users" ALTER COLUMN "kinde_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product_collection" ADD CONSTRAINT "product_collection_product_id_collection_id_pk" PRIMARY KEY("product_id","collection_id");--> statement-breakpoint
ALTER TABLE "customization_option" ADD COLUMN "image_url" varchar(255);--> statement-breakpoint
ALTER TABLE "customization_option" ADD COLUMN "texture" varchar(128);--> statement-breakpoint
ALTER TABLE "customization_option" ADD COLUMN "metadata" jsonb;--> statement-breakpoint
ALTER TABLE "site_users" ADD COLUMN "email_verified" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "site_users" ADD COLUMN "phone" varchar(20) DEFAULT '';--> statement-breakpoint
ALTER TABLE "site_users" ADD COLUMN "address" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "product_id" integer;--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "fabric_id" integer;--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "measurement_profile_id" uuid;--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "style_type" varchar(50);--> statement-breakpoint
ALTER TABLE "shop_order" ADD COLUMN "tracking_number" varchar(128);--> statement-breakpoint
ALTER TABLE "shop_order" ADD COLUMN "tracking_carrier" varchar(64);--> statement-breakpoint
ALTER TABLE "shop_order" ADD COLUMN "estimated_delivery_date" timestamp;--> statement-breakpoint
ALTER TABLE "shop_order" ADD COLUMN "currency" varchar(3) DEFAULT 'USD';--> statement-breakpoint
ALTER TABLE "shop_order" ADD COLUMN "tailor_notes" text;--> statement-breakpoint
ALTER TABLE "shop_order" ADD COLUMN "priority_level" varchar(20) DEFAULT 'standard';--> statement-breakpoint
ALTER TABLE "shop_order" ADD COLUMN "created_at" timestamp DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "shop_order" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_site_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."site_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_site_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."site_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_category" ADD CONSTRAINT "promotion_category_category_id_product_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."product_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_category" ADD CONSTRAINT "promotion_category_promotion_id_promotion_id_fk" FOREIGN KEY ("promotion_id") REFERENCES "public"."promotion"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_usage" ADD CONSTRAINT "promotion_usage_promotion_id_promotion_id_fk" FOREIGN KEY ("promotion_id") REFERENCES "public"."promotion"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_usage" ADD CONSTRAINT "promotion_usage_user_id_site_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."site_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promotion_usage" ADD CONSTRAINT "promotion_usage_order_id_shop_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."shop_order"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_request" ADD CONSTRAINT "refund_request_order_id_shop_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."shop_order"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_request" ADD CONSTRAINT "refund_request_user_id_site_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."site_users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_timeline" ADD CONSTRAINT "refund_timeline_refund_request_id_refund_request_id_fk" FOREIGN KEY ("refund_request_id") REFERENCES "public"."refund_request"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "promotion_usage_user_idx" ON "promotion_usage" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "refund_request_order_idx" ON "refund_request" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "refund_timeline_request_idx" ON "refund_timeline" USING btree ("refund_request_id");--> statement-breakpoint
ALTER TABLE "cart_item" ADD CONSTRAINT "cart_item_user_id_site_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."site_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_collection" ADD CONSTRAINT "product_collection_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_collection" ADD CONSTRAINT "product_collection_collection_id_collection_id_fk" FOREIGN KEY ("collection_id") REFERENCES "public"."collection"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_user_id_site_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."site_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_category" ADD CONSTRAINT "product_category_parent_id_product_category_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."product_category"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_measurements" ADD CONSTRAINT "user_measurements_user_id_site_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."site_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_fabric_id_fabric_id_fk" FOREIGN KEY ("fabric_id") REFERENCES "public"."fabric"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_shop_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."shop_order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_measurements" ADD CONSTRAINT "order_measurements_order_item_id_order_items_id_fk" FOREIGN KEY ("order_item_id") REFERENCES "public"."order_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_order" ADD CONSTRAINT "shop_order_user_id_site_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."site_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_measurement_user_id_idx" ON "user_measurements" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "order_items_order_id_idx" ON "order_items" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "order_measurements_item_id_idx" ON "order_measurements" USING btree ("order_item_id");--> statement-breakpoint
CREATE INDEX "shop_order_user_id_idx" ON "shop_order" USING btree ("user_id");